In [2]:
#How to create numpy/n-d arrays

In [3]:
import numpy as np

In [4]:
#numpy is library name and np is nickname of numpy

In [6]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr2=np.array([[1,2],[3,4]]) # 2-d array i.e matrix
arr2

array([[1, 2],
       [3, 4]])

In [9]:
type(arr2)

numpy.ndarray

In [13]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr6=np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [21]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [22]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [23]:
arr1

array([1, 2, 3, 4, 5])

In [24]:
arr1.shape

(5,)

In [25]:
arr2

array([[1, 2],
       [3, 4]])

In [26]:
arr2.shape

(2, 2)

In [27]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
arr9.shape

(2, 2, 2)

In [29]:
arr9.ndim  # it is check a dimension of array

3

In [31]:
arr1

array([1, 2, 3, 4, 5])

In [33]:
arr1.ndim

1

In [34]:
#size
arr1.size

5

In [35]:
arr9.size

8

In [37]:
arr9.itemsize

4

In [38]:
arr8.itemsize

8

In [39]:
#Dtype==>data type
arr8.dtype

dtype('float64')

In [40]:
arr9.dtype

dtype('int32')

In [41]:
arr9.astype('float') #it is convert of integer of float etc.

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [ ]:
#Numpy array vs Python List


In [44]:
lista=range(100)
arr11=np.arange(100)

In [45]:
import sys

In [46]:
#sys ==>system

In [47]:
print(sys.getsizeof(87)*len(lista))
#Why write 87 ?
#because 87 come 0 to 99 in b/w it is also present list

2800


In [49]:
print(arr11.itemsize*arr11.size)

400


In [50]:
#numpy is faster in comparsion of python list

In [51]:
import time

In [69]:
x=range(10000000)
y=range(10000000,20000000)


start_time=time.time()


c=[(x,y) for x,y in zip(x,y) ]


print(time.time()-start_time)

#Error! should had been
#c=[x+y for x,y in zip(x,y)]

5.155050039291382


In [70]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)

start_time=time.time()
c=a+b
print(time.time()-start_time)

1.5592601299285889


In [1]:
#Indexing,Slicing and Iteration


In [7]:
import numpy as np


In [12]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
arr1=np.array([1,2,3,4,5,6])
arr1


array([1, 2, 3, 4, 5])

In [16]:
arr1[2:4]

array([3, 4])

In [18]:
arr12[2]

array([ 8,  9, 10, 11])

In [25]:
arr12[2:4,1:3] #this opertion is slicing

array([[ 9, 10],
       [13, 14]])

In [28]:
arr12[1:4,2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [29]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [33]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [45]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])


In [46]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [47]:
arr1*arr2  #Vector multiplication

array([ 4, 10, 18, 28, 40, 54])

In [48]:
arr1*2 #Scalar multiplication

array([ 2,  4,  6,  8, 10, 12])

In [49]:
arr2 > 3

array([ True,  True,  True,  True,  True,  True])

In [62]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [57]:
arr1.dot(arr2)

154

In [58]:
arr1.dot(arr3)

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [59]:
arr4.max()

11

In [60]:
arr4.min()

6

In [61]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [63]:
arr4.min(axis=0)

array([6, 7])

In [64]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [65]:
arr4.sum()

51

In [66]:
arr4.sum(axis=0)

array([24, 27])

In [67]:
arr4.mean()

8.5

In [68]:
arr4.std()

1.707825127659933

In [69]:
arr4.var()

2.9166666666666665

In [70]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [71]:
np.median(arr4)

8.5

In [72]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])